export const INPUT_DATE_FORMAT = 'DD/MM/YYYY';

export const DATE_SHORT_TERM = 'D MMM';
export const DATE_MEDIUM_TERM = 'MMMM YY';
export const DATE_LONG_TERM = 'D MMM YY';

export const ONE_MINUTE_IN_SECONDS = 60;
export const FIFTEEN_MINUTES_IN_SECONDS = 15 * 60;
export const ONE_HOUR_IN_SECONDS = 60 * 60;
export const THIRTY_DAYS_IN_SECONDS = 30 * 24 * 60 * 60;
export const IBKR_CACHE_DURATION = THIRTY_DAYS_IN_SECONDS;

export const DISPLAY = {
  account: 'Account',
  activeCalls: 'Active calls',
  acquisitionCost: 'Acquisition cost',
  daysToEarnings: 'Days to earnings',
  amount: 'Amount',
  assignmentPct: 'Assignment %',
  avgCost: 'Avg cost',
  batchCode: 'Batch',
  cashEquivalentGBP: 'Cash equivalent GBP',
  closeTradePrice: 'Close trade price',
  costBasisDrop: 'Cost basis drop',
  currencyPair: 'Currency pair',
  current: 'Current',
  currentRate: 'Current rate',
  date: 'Date',
  daysTotal: 'Days total',
  differenceGBP: 'Difference GBP',
  differencePct: 'Difference %',
  dteCurrent: 'Current DTE',
  dteTotal: 'DTE',
  expiry: 'Expiry',
  high: 'High',
  highPct: 'High %',
  low: 'Low',
  lowPct: 'Low %',
  netCost: 'Net cost',
  partialBatch: 'Partial batch',
  partialBatchAcquisitionCost: 'Acquisition cost',
  partialBatchQuantity: 'Quantity',
  profitGBP: 'Profit GBP',
  priceIncreaseGBP: 'Price increase GBP',
  purchaseNetCost: 'Net cost',
  purchaseQuantity: 'Quantity',
  putOnly: 'Put only',
  putOnlyPremium: 'Premium',
  rate: 'Rate',
  return1YPctIfAssigned: 'Return 1Y % if assigned',
  return30DPctExpected: 'Return 30D % expected',
  return30DPctEffective: 'Return 30D % effective',
  return30DPctResidual: 'Return 30D % residual',
  return30DPctLastCall: 'Return 30D % last call',
  returnGBP: 'Return GBP',
  returnGBPIfAssigned: 'Return GBP if assigned',
  return30DPctIfAssigned: 'Return 30D % if assigned',
  returnGBPLastCall: 'Return GBP last call',
  returnPct: 'Return %',
  returnPctIfAssigned: 'Return % if assigned',
  status: 'Status',
  stockPrice: 'Stock price',
  strike: 'Strike',
  summary: 'Summary',
  tradePrice: 'Trade price',
  ticker: 'Ticker',
  totalQuantity: 'Total quantity',
  valueGBP: 'Value GBP',
  unitAcquisitionCost: 'Acquisition cost',
  wheeled: 'Wheeled',
  wheeledQuantity: 'Quantity',
  wheeledExitValue: 'Exit value',
  wheeledAcquisitionCost: 'Acquisition cost',
  wheeledPremium: 'Premium',
  wheeledPremiumAsPctOfReturn: '%',
  wheeledGrowth: 'Growth',
  wheeledGrowthAsPctOfReturn: '%',
  wheeledReturn: 'Return',
  wheeledReturnPct: '%',
  wheeling: 'Wheeling',
  wheelingAcquisitionCost: 'Acquisition cost',
  wheelingPremium: 'Premium',
  wheelingQuantity: 'Quantity',
};
